import type { Config } from "tailwindcss";

/**
 * Design tokens ported 1:1 from the approved Stitch export
 * (stitch_noor_islamic_academy_website.zip -> code.html / DESIGN.md).
 * The rendered code.html + screen.png are treated as the visual source of
 * truth (see project notes) rather than DESIGN.md's prose description,
 * which used a different, unused palette.
 */
const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./content/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-error-container": "#93000a",
        "surface-container-low": "#eaf6f8",
        "on-background": "#121d1f",
        "tertiary-fixed": "#b4efd6",
        "on-primary-fixed": "#002116",
        "surface-container-highest": "#d9e5e7",
        "inverse-on-surface": "#e7f3f5",
        "surface-tint": "#3b6756",
        "on-tertiary-fixed-variant": "#15503e",
        "on-primary": "#ffffff",
        error: "#ba1a1a",
        "surface-container-high": "#deeaed",
        "secondary-fixed": "#ffdea5",
        "primary-fixed-dim": "#a2d1bb",
        "inverse-surface": "#273234",
        "secondary-container": "#fed488",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#effcfe",
        "on-secondary-fixed-variant": "#5d4201",
        "primary-fixed": "#bdedd7",
        "on-surface-variant": "#414944",
        "on-primary-fixed-variant": "#224f3f",
        "tertiary-container": "#003c2c",
        tertiary: "#002419",
        "on-surface": "#121d1f",
        primary: "#002419",
        "outline-variant": "#c0c8c3",
        "surface-dim": "#d0dcdf",
        "inverse-primary": "#a2d1bb",
        "primary-container": "#0b3b2c",
        "on-secondary-container": "#785a1a",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#261900",
        "surface-variant": "#d9e5e7",
        "tertiary-fixed-dim": "#99d3ba",
        outline: "#717974",
        "error-container": "#ffdad6",
        "on-tertiary-fixed": "#002117",
        "on-primary-container": "#78a692",
        background: "#effcfe",
        "on-tertiary-container": "#6fa891",
        "on-tertiary": "#ffffff",
        surface: "#effcfe",
        secondary: "#775a19",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#e9c176",
        "surface-container": "#e4f0f2",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "space-3xs": "0.125rem",
        "space-2xs": "0.25rem",
        "space-xs": "0.5rem",
        "space-sm": "0.75rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-2xl": "3rem",
        "space-3xl": "4rem",
        "space-4xl": "6rem",
        "gutter-mobile": "1rem",
        "gutter-desktop": "2rem",
        "container-max": "80rem",
      },
      maxWidth: {
        "container-max": "80rem",
      },
      fontFamily: {
        "display-lg": ["var(--font-playfair)", "Georgia", "serif"],
        "display-lg-mobile": ["var(--font-playfair)", "Georgia", "serif"],
        "display-md": ["var(--font-playfair)", "Georgia", "serif"],
        "display-md-mobile": ["var(--font-playfair)", "Georgia", "serif"],
        "headline-lg": ["var(--font-playfair)", "Georgia", "serif"],
        "headline-md": ["var(--font-playfair)", "Georgia", "serif"],
        "headline-sm": ["var(--font-playfair)", "Georgia", "serif"],
        "title-lg": ["var(--font-jakarta)", "system-ui", "sans-serif"],
        "title-md": ["var(--font-jakarta)", "system-ui", "sans-serif"],
        "title-sm": ["var(--font-jakarta)", "system-ui", "sans-serif"],
        "body-lg": ["var(--font-jakarta)", "system-ui", "sans-serif"],
        "body-md": ["var(--font-jakarta)", "system-ui", "sans-serif"],
        "body-sm": ["var(--font-jakarta)", "system-ui", "sans-serif"],
        "label-lg": ["var(--font-jakarta)", "system-ui", "sans-serif"],
        "label-md": ["var(--font-jakarta)", "system-ui", "sans-serif"],
        "label-sm": ["var(--font-jakarta)", "system-ui", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["56px", { lineHeight: "64px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "display-md": ["44px", { lineHeight: "52px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "display-md-mobile": ["30px", { lineHeight: "38px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-md": ["26px", { lineHeight: "34px", fontWeight: "600" }],
        "headline-sm": ["22px", { lineHeight: "30px", fontWeight: "600" }],
        "title-lg": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "title-md": ["18px", { lineHeight: "26px", fontWeight: "600" }],
        "title-sm": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.06em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};

export default config;
